"""Initial Migration

Revision ID: 9d34936efbab
Revises: 04952160ec55
Create Date: 2021-08-25 17:04:26.081486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d34936efbab'
down_revision = '04952160ec55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pitchs_message_key', 'pitchs', type_='unique')
    op.drop_constraint('post_like_comment_key', 'post_like', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('post_like_comment_key', 'post_like', ['comment'])
    op.create_unique_constraint('pitchs_message_key', 'pitchs', ['message'])
    # ### end Alembic commands ###
